POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "My Second Blog",
    "author": "Manuel Maria Félix",
    "url": "www.myblog2.com",
    "likes": 34
}

####

GET http://localhost:3003/api/blogs