POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "My Third Blog",
    "author": "Manuel Fonseca Félix",
    "url": "www.myblog3.com",
    "likes": 45
}

####

GET http://localhost:3003/api/blogs